version: 0.0
os: linux
files:
        - source: /
          destination: /opt/build
          overwrite: true
          
permission:
        - object: codedeploy
          pattern: "*.sh"
          onwer: root
          group: root
          mode: 777
          type:
                  - files

hooks:
        BeforeInstall:
                - location: codedeploy/beforebuild.sh
        AfterInstall:
                - location: codedeploy/build.sh
        ApplicationStart:
                - location: codedeploy/afterbuild.sh
        ValidateService:
                - location: codedeploy/deploy.sh
